# config

# interval in mins
interval: 1000000

bbdc:
  username: ""
  password: ""

chromedriver:
  host: http://localhost:4444

booking:
  want_sessions: ["1", "2", "3", "4", "5", "6", "7", "8", "9"]

telegram:
  enabled: True
  token: "7370969996:AAE9fSlNd-cvuT2Ff8mvTT4iqSVureeZYJM"
  chat_id: "-1002153047381"

months:
  month: "JUN'24"
